---
# Possible RKE2 Channels
channels:
  - stable
  - latest
  - v1.18
  - v1.19
  - v1.20
  - v1.21
  - v1.22
  - v1.23
  - v1.24
  - v1.25
  - v1.26
  - v1.27
  - v1.28
installed: false
rke2_version_changed: false
custom_ca_cert_files:
  - server-ca.crt
  - server-ca.key
  - client-ca.key
  - client-ca.crt
  - request-header-ca.crt
  - request-header-ca.key
  - etcd/peer-ca.crt
  - etcd/peer-ca.key
  - etcd/server-ca.crt
  - etcd/server-ca.key
  - service.key
